diffusion_config :
     sigma_min : 0.002
     sigma_max : 13.
     log_mean : -1.  
     log_std : 1.2  
     num_workers : 8  

optim_config :
     lr : 1e-4  

denoiser_config :
     sigma_data : 1.  
     sigma_min : 0.002  
     sigma_max : 10.  
     sigma_disc : 1000  
     input_dim : 6  
     embed_dim : 256  
     channel_mult : [1  2  3, 4, ]


trainer_config:
     max_epochs: 1000
     accelerator: "cpu"  # o "gpu"
     devices: 1
     batch_size: 5000
     total_samples: 5_000_000
     batch_gen: 10_000
     n_steps: 200
     strategy: "auto"  # o "ddp"
     num_workers: 0
     size_training: 100_000




