diffusion_config :
     sigma_min : 0.002   
     sigma_max : 7.
     log_mean : -1.   
     log_std : 1.2
     num_workers : 6  

optim_config :
     lr : 1e-4   

denoiser_config :
     sigma_data : 2.5   
     sigma_min : 0.0002
     sigma_max : 7
     sigma_disc : 1000   
     input_dim : 2
     embed_dim : 256   
     channel_mult : [ 2,   4,   4,   2]

normalization : False

trainer_config:
     max_epochs: 1500
     accelerator: "gpu"
     devices: -1
     batch_size: 10_000
     batch_gen: 50_000
     n_steps: 200
     strategy: "ddp"
     num_workers: 6
     






