diffusion_config :
     sigma_min : 0.002   
     sigma_max : 15.
     log_mean : -1.   
     log_std : 1.2
     num_workers : 0 #8

optim_config :
     lr : 1e-4   

denoiser_config :
     sigma_data : 1.   
     sigma_min : 0.002
     sigma_max : 15   
     sigma_disc : 1000   
     input_dim : 3
     embed_dim : 256   
     channel_mult : [2 ,  2]

normalization: True

trainer_config:
     max_epochs: 1000
     accelerator: "cpu"  # o "gpu"
     devices: 1
     batch_size: 5000
     total_samples: 5_000_000
     batch_gen: 10_000
     n_steps: 200
     strategy: "auto"  # o "ddp"
     num_workers: 0
     size_training: 100_000


